### ISSUE TITLE
Verify TrashTaf runs on Ubuntu with Chrome

### ISSUE THREAD

**Issue by rf-eggnine** [rf-eggnine/TrashTaf#19]
1. Given https://github.com/rf-eggnine/TrashTaf/issues/1 passes
2. When Context is read
3. OperatingSystemName is Ubuntu
4. And BrowserName is Chrome

**Comment by rf-eggnine** [comment]
When running on Ubuntu Chrome Webdriver reports in logs that it starts successfully, but it never returns the WebDriver to the calling method. Instead, after 60 it throws a WebDriverException with the message

>    OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:41533/session timed out after 60 seconds.
---- System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
-------- System.TimeoutException : The operation was canceled.
------------ System.Threading.Tasks.TaskCanceledException : The operation was canceled.
---------------- System.IO.IOException : Unable to read data from the transport connection: Operation canceled.
-------------------- System.Net.Sockets.SocketException : Operation canceled

and the stack trace:
> at OpenQA.Selenium.Remote.HttpCommandExecutor.ExecuteAsync(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.ExecuteAsync(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.ExecuteAsync(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities capabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at Eggnine.TrashTaf.XUnit.TrashTafTestAdapter.<>c__DisplayClass2_0.<ExecuteTest>b__3() in /home/runner/work/TrashTaf/TrashTaf/Eggnine.TrashTaf.XUnit/TrashTafTestAdapter.cs:line 96
